# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import random
from PyQt5 import QtCore, QtGui, QtWidgets

import model
import analyze2


def get_data(name, password1):
    sql = "SELECT * FROM stu WHERE names='" + name + "' and passwd = '" + password1 + "' "
    data = model.sql_select(sql)
    return data


def suggest():
    suggest_list = ["不要让你的弱项成为你拖的后腿，请保持住你的强项，多花一点时间到弱项上。",
                    "合理分配时间，不浪费时间，进行查漏补缺。",
                    "考好的科目的不要懈怠，考差了也不要气馁，保持积极的心态。",
                    "多学点学习方法，可以用更短的时间干更多的事情。",
                    "如果你想提高分数，你首先要上好课，认真听讲。",
                    "面对你的短板，请不要放弃，可能你再努力一点，你就能提高了。",
                    "你可以选择好的教辅材料和卷子来练习，但也得根据自己的学习情况来做。",
                    "如果再学习上有问题，请及时问，不要积压，这样子才能有收获",
                    "发现短板要趁早补，不要等到第二天才去做。"]
    suggest = random.choice(suggest_list)
    # print(suggest)
    return suggest


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 100, 751, 131))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        self.title1 = QtWidgets.QLabel(self.centralwidget)
        self.title1.setGeometry(QtCore.QRect(310, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(19)
        self.title1.setFont(font)
        self.title1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.title1.setAlignment(QtCore.Qt.AlignCenter)
        self.title1.setObjectName("title1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 470, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.bad = QtWidgets.QLabel(self.centralwidget)
        self.bad.setGeometry(QtCore.QRect(400, 250, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.bad.setFont(font)
        self.bad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bad.setAlignment(QtCore.Qt.AlignCenter)
        self.bad.setObjectName("bad")
        self.goodtext = QtWidgets.QLabel(self.centralwidget)
        self.goodtext.setGeometry(QtCore.QRect(196, 260, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.goodtext.setFont(font)
        self.goodtext.setAlignment(QtCore.Qt.AlignCenter)
        self.goodtext.setObjectName("goodtext")
        self.tops = QtWidgets.QLabel(self.centralwidget)
        self.tops.setGeometry(QtCore.QRect(110, 320, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.tops.setFont(font)
        self.tops.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tops.setAlignment(QtCore.Qt.AlignCenter)
        self.tops.setObjectName("tops")
        self.percenttext = QtWidgets.QLabel(self.centralwidget)
        self.percenttext.setGeometry(QtCore.QRect(580, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.percenttext.setFont(font)
        self.percenttext.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.percenttext.setObjectName("percenttext")
        self.good = QtWidgets.QLabel(self.centralwidget)
        self.good.setGeometry(QtCore.QRect(110, 250, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.good.setFont(font)
        self.good.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.good.setAlignment(QtCore.Qt.AlignCenter)
        self.good.setObjectName("good")
        self.badtxet = QtWidgets.QLabel(self.centralwidget)
        self.badtxet.setGeometry(QtCore.QRect(480, 260, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.badtxet.setFont(font)
        self.badtxet.setAlignment(QtCore.Qt.AlignCenter)
        self.badtxet.setObjectName("badtxet")
        self.toptext = QtWidgets.QLabel(self.centralwidget)
        self.toptext.setGeometry(QtCore.QRect(250, 330, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.toptext.setFont(font)
        self.toptext.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.toptext.setObjectName("toptext")
        self.percent = QtWidgets.QLabel(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(400, 320, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.percent.setFont(font)
        self.percent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.percent.setAlignment(QtCore.Qt.AlignCenter)
        self.percent.setObjectName("percent")
        self.suggest = QtWidgets.QLabel(self.centralwidget)
        self.suggest.setGeometry(QtCore.QRect(70, 390, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.suggest.setFont(font)
        self.suggest.setAlignment(QtCore.Qt.AlignCenter)
        self.suggest.setObjectName("suggest")
        self.suggesttext = QtWidgets.QLabel(self.centralwidget)
        self.suggesttext.setGeometry(QtCore.QRect(260, 390, 401, 51))
        self.suggesttext.setObjectName("suggesttext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.open_html2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        f = open('a.txt', encoding='UTF-8')
        line = f.readline().strip()  # 读取第一行
        txt = []
        txt.append(line)
        while line:  # 直到读取完文件
            line = f.readline().strip()  # 读取一行文件，包括换行符
            txt.append(line)
        global name
        name = txt[0]
        global password
        password = txt[1]
        # print(name)
        # print(password)
        f.close()
        sql = f"SELECT * FROM stu WHERE names='{name}'"
        data = model.sql_select(sql)
        data = int(data[11])
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生成绩系统"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "单人"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "座号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "语文"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "数学"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "英语"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "政治"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "历史"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "地理"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "物理"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "化学"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "生物"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "总分"))
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[0]}"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[1]}"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[2]}"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[3]}"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[4]}"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[5]}"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[6]}"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[7]}"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[8]}"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[9]}"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[10]}"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("widget", f"{get_data(name=name, password1=password)[11]}"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setSortingEnabled(False)
        # self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.title1.setText(_translate("MainWindow", "你的成绩"))
        self.pushButton.setText(_translate("MainWindow", "查看智能分析"))
        self.bad.setText(_translate("MainWindow", "弱项："))
        self.goodtext.setText(_translate("MainWindow", f"{model.good(student=name)}"))
        self.tops.setText(_translate("MainWindow", "排名："))
        self.percenttext.setText(_translate("MainWindow", f"{model.percent(student=name, config=0)}"+"%"))
        self.good.setText(_translate("MainWindow", "强项："))
        self.badtxet.setText(_translate("MainWindow", f"{model.bad(student=name)}"))
        self.toptext.setText(_translate("MainWindow", f"{model.tops(model.percent(student=name, config=1))}/98"))
        self.percent.setText(_translate("MainWindow", "总得分率："))
        self.suggest.setText(_translate("MainWindow", "建议与总结："))
        self.suggesttext.setText(_translate("MainWindow", f"{suggest()}"))

    def open_html2(self):
        f = open('a.txt', encoding='UTF-8')
        line = f.readline().strip()  # 读取第一行
        txt = []
        txt.append(line)
        while line:  # 直到读取完文件
            line = f.readline().strip()  # 读取一行文件，包括换行符
            txt.append(line)
        global name
        name = txt[0]
        global password
        password = txt[1]
        # print(name)
        # print(password)
        f.close()
        a = get_data(name=name, password1=password)
        # print(a)
        result = []
        for i in range(0, len(a)):
            result.append(a[i])
        result = result[2:11]
        # print(result)
        result09 = []
        for j in range(0, len(result)):
            result09.append(int(result[j]))
        analyze2.students_self(result09)
        os.startfile(os.getcwd() + r"\你的水平vs顶尖水平.html")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    # MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)  # 只显示关闭按钮
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())
